version: "3.7"
services:
  api:
    container_name: api
    build:
      context: .
    tty: true
    depends_on:
      - cache
    restart: unless-stopped
    ports:
      - "${APP_PORT}:${APP_PORT}"
      - "${APP_DEBUGGER_PORT}:${APP_DEBUGGER_PORT}"
    networks:
      - backend
      - cache
    volumes:
      - ./:/srv/app
      - /srv/app/node_modules
    command: npm run start:dev

  cache:
    container_name: cache
    image: redis
    ports:
      - '6379:6379'
    command: redis-server --save 60 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    networks:
      - cache
    volumes:
      - cache:/data
    restart: unless-stopped


networks:

  backend:
    driver: bridge
  cache:
    driver: bridge

volumes:
  cache:
    driver: local
    labels:
      mf.project.name: ${APP_NAME}
